// Maps the nationality/country strings returned by the Ergast/Jolpica-F1 API
// (driver nationality is a demonym, circuit Location.country is a country name)
// to ISO 3166-1 alpha-2 codes, used to build flagcdn.com URLs.
export const COUNTRY_TO_ISO2: Record<string, string> = {
  // Driver nationalities (demonyms) - current grid plus common F1-adjacent nationalities
  Argentine: 'ar',
  American: 'us',
  Australian: 'au',
  Austrian: 'at',
  Belgian: 'be',
  Brazilian: 'br',
  British: 'gb',
  Canadian: 'ca',
  Chinese: 'cn',
  Colombian: 'co',
  Czech: 'cz',
  Danish: 'dk',
  Dutch: 'nl',
  Finnish: 'fi',
  French: 'fr',
  German: 'de',
  Hungarian: 'hu',
  Indian: 'in',
  Indonesian: 'id',
  Irish: 'ie',
  Italian: 'it',
  Japanese: 'jp',
  Mexican: 'mx',
  Monegasque: 'mc',
  'New Zealander': 'nz',
  Polish: 'pl',
  Portuguese: 'pt',
  Russian: 'ru',
  'South African': 'za',
  Spanish: 'es',
  Swedish: 'se',
  Swiss: 'ch',
  Thai: 'th',
  Venezuelan: 've',

  // Circuit countries (country names) - current calendar plus common historical entries
  Argentina: 'ar',
  Australia: 'au',
  Austria: 'at',
  Azerbaijan: 'az',
  Belgium: 'be',
  Brazil: 'br',
  Canada: 'ca',
  China: 'cn',
  France: 'fr',
  Germany: 'de',
  Hungary: 'hu',
  India: 'in',
  Italy: 'it',
  Japan: 'jp',
  Malaysia: 'my',
  Mexico: 'mx',
  Monaco: 'mc',
  Netherlands: 'nl',
  Portugal: 'pt',
  Qatar: 'qa',
  Russia: 'ru',
  'Saudi Arabia': 'sa',
  Singapore: 'sg',
  'South Korea': 'kr',
  Spain: 'es',
  Turkey: 'tr',
  UAE: 'ae',
  UK: 'gb',
  USA: 'us',
};

export function countryToIso2(countryOrNationality: string): string | null {
  return COUNTRY_TO_ISO2[countryOrNationality] ?? null;
}
